Account Screen Enhancements Completed
liveasy97/shipperApp pull request #35
Opened 2023-09-14 14:52 UTC by Ut321

The work on the account screen for both Android and web platforms has been successfully completed.

Users now have the ability to edit their account details. Once they make the desired changes, they can save the updated information.

Additionally, users can send invitations to others using the dedicated invite button located within the account screen. This feature enhances user engagement and interaction on the platform

2023-09-16 18:44 UTC, Anik-Chakraborty commented on assets/icons/accountarrow.png
Remove this png and use Icons.keyboard_backspace instead

2023-09-16 18:44 UTC, Anik-Chakraborty commented on pubspec.lock
Remove this pubspec.lock as it is a autogenerated file.

2023-09-16 19:02 UTC, chirag4601 commented on lib/Widgets/accountWidgets/label_text.dart
> +          color: Color(0xFF152968),
use these constants from constants folder

2023-09-16 19:19 UTC, chirag4601 requested changes

2023-09-16 19:19 UTC, chirag4601 commented on lib/Widgets/accountWidgets/label_text.dart
> +class LabelTextWidget extends StatelessWidget {
Name doesn't align with it its features. You have named this widget as LabelText and it returns a Text Field

2023-09-16 19:19 UTC, chirag4601 commented on lib/screens/accountScreens/account_details.dart
> +import '../../Widgets/headingTextWidget.dart';
Use Package Imports instead of these

2023-09-16 19:19 UTC, chirag4601 commented on lib/screens/accountScreens/account_details.dart
> +                  ListTile(
Why Not move this ListTile inside of your LabelTextWidget, as there is a lot of redundant code here. 
Also, A better practise to make such 5 widgets one after other can be to create a array of properties and the use array.map to create such widgets. If such thing cannot be implemented here, you can ignore the last part

2023-09-16 19:19 UTC, chirag4601 commented on lib/screens/accountScreens/account_details.dart
> +  Widget build(BuildContext context) {
There is a lot of repeted code in this file and also this file is way too big. Try to break it into smaller components.

2023-09-24 11:09 UTC, chirag4601 approved these changes

2023-09-24 11:09 UTC, merged