Complete screen UI update
liveasy97/shipperApp pull request #38
Opened 2023-09-22 10:48 UTC by Anik-Chakraborty

1. Update UI of complete screen loads for web and fix missing data issues.
2. Change the navigator of complete screens loads to Document upload screen.
3. Added feature called add missing place in post load loading unloading places.

2023-09-22 17:28 UTC, chirag4601 requested changes

2023-09-22 17:28 UTC, chirag4601 commented on lib/Widgets/deliveredCard.dart
> +    double textFontSize;
all this can be done in a single line with a tertiary operator

2023-09-22 17:28 UTC, chirag4601 commented on lib/Widgets/loadPosterDetails.dart
> +              loadPosterCompanyApproved ?? false
why "?? false"?

2023-09-22 17:28 UTC, chirag4601 commented on lib/Widgets/deliveredCard.dart
> +                moveToDocumentUploadScreen();
instead of implementing separation on the top level, try to see if anything is common and then for the part that is different on the web and mobile, use this check

2023-09-25 08:04 UTC, Anik-Chakraborty commented on lib/Widgets/deliveredCard.dart
> +                moveToDocumentUploadScreen();
The deliveredCard UI is totally different for mobile and desktop.
In desktop it is represented in a row wheares for mobile it is in card form.
If i will use one GestureDetector both for mobile and desktop then it throws 'Incorrect use of ParentDataWidget' error for mobile.

2023-09-25 08:04 UTC, Anik-Chakraborty commented on lib/Widgets/deliveredCard.dart
> +    double textFontSize;
Done

2023-09-25 08:07 UTC, Anik-Chakraborty commented on lib/Widgets/loadPosterDetails.dart
> +              loadPosterCompanyApproved ?? false
I have used ?? this for null check.
As loadPosterCompanyApproved can be null for this reason I have make it false as default value otherwise for some cases it throws null error.

2023-09-26 17:52 UTC, merged