Added try again screen, added shimmer effect and improved the response of fastag api
liveasy97/shipperApp pull request #48
Opened 2023-10-27 06:04 UTC by aman-netizen-ux

2023-10-30 12:06 UTC, Anik-Chakraborty commented
![image](https://github.com/liveasy97/shipperApp/assets/79321628/74462b0f-812d-47e4-bf3a-29eb1bc9abba)
these try again button doesn't work at least it should show the loading effect and then show try again even no data is there

![image](https://github.com/liveasy97/shipperApp/assets/79321628/f853c390-a101-49d2-a4a4-11c49cf30ef2)
also the back button doesn't work in try again screen.

2023-10-30 12:10 UTC, Anik-Chakraborty commented
for truck no CG07BC9186 the left timeline renders very _**strangely**_
![image](https://github.com/liveasy97/shipperApp/assets/79321628/de6616d3-8cda-48f5-8c71-7e90ecb485d0)

2023-10-30 12:11 UTC, Anik-Chakraborty requested changes

2023-10-30 12:11 UTC, Anik-Chakraborty reviewed
Found this error in terminal while testing.... handle this exception because in production it might cause problem.
location from timeline : null
500
Error: NoSuchMethodError: '[]'
Dynamic call of null.
Receiver: null
Arguments: [0]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 813:3   defaultNoSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 807:56  noSuchMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 283:12  callNSM
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 294:25  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 435:5   dsend
packages/shipper_app/functions/ongoingTrackUtils/FastTag.dart 25:52               getVehicleLocation
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15               <fn>

2023-11-01 07:20 UTC, Anik-Chakraborty commented
![image](https://github.com/liveasy97/shipperApp/assets/79321628/ced8de5c-103b-4d86-8659-123fea1cce90)
getting this error when resizing the browser window from desktop to mobile or mobile screen size

Expected a value of type 'Set<Polyline>', but got one of type 'List<Set<Polyline>>'

The relevant error-causing widget was: 
  MobileMap MobileMap:file:///D:/shipperAppLiveasy/lib/screens/FastTagScreen.dart:296:14

2023-11-01 07:52 UTC, Anik-Chakraborty commented on lib/functions/ongoingTrackUtils/FastTag.dart
>        debugPrint('API Error: ${response.statusCode} - ${response.body}');
Rather than printing the response body ... just debug print the error message only

2023-11-01 09:21 UTC, aman-netizen-ux commented on lib/functions/ongoingTrackUtils/FastTag.dart
>        debugPrint('API Error: ${response.statusCode} - ${response.body}');
Resolved this issue.

2023-11-01 15:23 UTC, Anik-Chakraborty approved these changes

2023-11-02 12:44 UTC, liveasy97 approved these changes

2023-11-02 12:44 UTC, merged