work on Invoice Screen
liveasy97/shipperApp pull request #58
Opened 2023-11-16 09:19 UTC by Ut321

Update Invoice Screen where User Can see the Invoice Details.

2023-11-16 14:27 UTC, Anik-Chakraborty requested changes

2023-11-16 14:27 UTC, Anik-Chakraborty commented on lib/screens/Invoice_screen.dart
> +    String shipperId = shipperIdController.shipperId.value;
instead of shipperIdController.shipperId.value use shipperIdController.ownerShipperId.value so that employee can also see same data

2023-11-16 16:50 UTC, Ut321 commented on lib/screens/Invoice_screen.dart
> +    String shipperId = shipperIdController.shipperId.value;
Done

2023-11-17 11:47 UTC, Anik-Chakraborty approved these changes

2023-11-17 11:50 UTC, merged