Completed the Eway Bills Screen
liveasy97/shipperApp pull request #86
Opened 2023-12-11 16:57 UTC by aman-netizen-ux

2023-12-11 18:06 UTC, Anik-Chakraborty requested changes

2023-12-11 18:06 UTC, Anik-Chakraborty commented on lib/screens/Eway_Bills_Screen.dart
> +                      //     bottom: screenHeight * 0.06, ),
remove these commented codes

2023-12-11 18:06 UTC, Anik-Chakraborty commented on lib/screens/TransporterOrders/documentUploadScreen.dart
> +                                                                          // unloadingPointCity:
Here as well.

2023-12-11 18:06 UTC, Anik-Chakraborty commented on lib/screens/FastTagScreen.dart
> +      // this.loadingPointCity,
:)

2023-12-12 10:09 UTC, liveasy97 approved these changes

2023-12-12 10:09 UTC, merged